import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Sidebar } from "lucide-react";
import Sidebarm from "@/components/sidebar"
import { ThemeProvider } from "@/components/themeprovider";
import { ModeToggle } from "@/components/theme-toggle";
import Header from "@/components/header";
import { EdgeStoreProvider } from '../lib/edgestore';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex items-start justify-between`}>
        <Sidebarm/>
        <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <main className="grid w-full h-full pl-[300px]">
              <Header />
              <div className="p-4">
                <EdgeStoreProvider>
                  {children}
                </EdgeStoreProvider>
              </div>
            </main>
          </ThemeProvider>
        
      </body>
    </html>
  );
}
